fix: or-894 invert condition for key removal
Informatievlaanderen/organisation-registry pull request #582
Opened 2022-05-03 13:59 UTC by QuintenGreenstack

2022-05-03 18:52 UTC, koenmetsu commented on src/OrganisationRegistry/Organisation/Organisation.cs
> +            if (State.OrganisationKeys.Any(key => key.OrganisationKeyId == organisationKeyId))
Reading this, it feels weird. Maybe change to `if !Any(...) return` again?

2022-05-03 18:53 UTC, koenmetsu commented on test/OrganisationRegistry.UnitTests/KeyTypes/RemoveKeyType/WhenRemovingAKeyType.cs
> +        public void AnKeyTypeRemovedEventIsPublished()
Typo `AnKeyType`

2022-05-03 19:00 UTC, koenmetsu requested changes
Nice PR, minor changes requested.

2022-05-04 07:39 UTC, W0dan commented on test/OrganisationRegistry.UnitTests/KeyTypes/RemoveKeyType/WhenRemovingAKeyType.cs
> +        protected override int ExpectedNumberOfEvents
dat ligt aan de regel om bij expression bodied members de => altijd op de volgende lijn te laten beginnen denk'

2022-05-04 14:55 UTC, W0dan approved these changes

2022-05-04 14:57 UTC, merged

2022-05-04 15:25 UTC, koenmetsu commented
:tada: This PR is included in version 1.176.1 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/organisation-registry/releases/tag/v1.176.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: